-- Create the schema (database) if it doesn't exist
CREATE DATABASE IF NOT EXISTS aacalib;
USE aacalib;

-- Create table REGFDB
CREATE TABLE IF NOT EXISTS REGFDB (
    ID INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Unique ID',
    RMSACCTNUM VARCHAR(255) NULL COMMENT 'ACCT NUMBER',
    DEPONAME VARCHAR(255) NULL COMMENT 'DEPOSITOR NAME',
    DEPOADDR VARCHAR(255) NULL COMMENT 'DEPOSITOR ADDRESS',
    ACCRUEDINTEREST DECIMAL(20,4) NULL COMMENT 'ACCRUED INTEREST',
    PRINCIPAL DECIMAL(20,4) NULL COMMENT 'PRINCIPAL AMOUNT',
    RENEWALAMOUNT DECIMAL(20,4) NULL COMMENT 'RENEWAL AMOUNT',
    NOOFRENEWALS INT NULL COMMENT 'NUMBER OF RENEWALS',
    STATUSFLAG VARCHAR(10) NULL COMMENT 'STATUS',
    BRANCHCODE VARCHAR(50) NULL COMMENT 'BRANCH CODE',
    ENTRYDATE DATE NULL COMMENT 'ENTRY DATE',
    ENTEREDBY VARCHAR(255) NULL COMMENT 'ENTERED BY',
    AUTHBY VARCHAR(255) NULL COMMENT 'AUTHORIZED BY',
    AUTHTIME DATETIME NULL COMMENT 'AUTHORIZATION TIME',
    UPDTIME DATETIME NULL COMMENT 'UPDATE TIME',
    DELETEDFLAG CHAR(1) NULL COMMENT 'DELETED FLAG',
    INTERESTRATE DECIMAL(5,2) NULL COMMENT 'INTEREST RATE',
    RENEWALDATE DATE NULL COMMENT 'RENEWAL DATE',
    SCHEME VARCHAR(50) NULL COMMENT 'SCHEME',
    OPENINGDATE DATE NULL COMMENT 'OPENING DATE',
    ORIGINALDATE DATE NULL COMMENT 'ORIGINAL DATE',
    MATURITYDATE DATE NULL COMMENT 'MATURITY DATE',
    DEPOSITORID VARCHAR(100) NULL COMMENT 'DEPOSITOR ID',
    NOMINEE VARCHAR(255) NULL COMMENT 'NOMINEE NAME',
    NOMINEEADDR VARCHAR(255) NULL COMMENT 'NOMINEE ADDRESS',
    PANNO VARCHAR(20) NULL COMMENT 'PAN NUMBER',
    TAXSTATUS VARCHAR(50) NULL COMMENT 'TAX STATUS'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='REGULAR FD MASTER TABLE';
